# Generated by Django 4.0.4 on 2022-05-12 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('szul_date', models.DateField()),
                ('taj', models.CharField(max_length=255)),
                ('nem', models.CharField(choices=[('n', 'Nő'), ('f', 'Férfi')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('nem', models.CharField(choices=[('n', 'Nő'), ('m', 'Mind'), ('f', 'Férfi')], max_length=10)),
                ('kor', models.IntegerField()),
                ('interval', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kezeles', models.TextField()),
                ('ido', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatments', to='patient.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Tested',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utolso', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='patient.patient')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='patient.test')),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gyogyszer', models.CharField(max_length=255)),
                ('treatment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicines', to='patient.treatment')),
            ],
        ),
    ]
